server:
  port: 8080
  host: 0.0.0.0
  api_prefix: /miicapi

database:
  host: '10.3.1.95'
  port: 3305
  username: 'root'
  password: '1qaz@WSX'
  dbname: 'caam_portal'
  charset: 'utf8mb4'
  parse_time: true
  loc: 'Asia/Shanghai'
  timeout: '5s'
  read_timeout: '10s'
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600
  conn_max_idle_time: 600

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0
  db1: 1


jwt:
  secret: your-256-bit-secret-key-here-must-be-at-least-32-characters
  expires_hour: 24

log:
  level: info
  path: ./logs
