package service

import (
	"application/internal/models"
	"application/pkg/db"
)

// Notification types generated by the workflow.
const (
	NotifyTypeApplication = "application"
	NotifyTypeReview      = "review"
	NotifyTypeResult      = "result"
	NotifyTypeCertificate = "certificate"
)

// notifyUser writes a site message for an applicant. Best effort: failures are
// ignored so a notification problem never breaks the state transition.
func notifyUser(userID uint64, title, content, ntype string) {
	if userID == 0 {
		return
	}
	db.DB.Create(&models.Notification{
		UserID:  userID,
		Title:   title,
		Content: content,
		Type:    ntype,
	})
}
